A3
SQL(SELECT YE.ZWSSFZYE_DWBH,HSDW.LSWLDW_DWMC,YE.ZWSSFZYE_WLDWBH,WLDW.LSWLDW_DWMC,ZWSSFZYE_DFLJ FROM ZWSSFZYE@YY@ YE LEFT JOIN LSWLDW HSDW ON HSDW.LSWLDW_WLDWBH=YE.ZWSSFZYE_DWBH LEFT JOIN LSWLDW WLDW ON WLDW.LSWLDW_WLDWBH=YE.ZWSSFZYE_WLDWBH WHERE (HSDW.HelpTag LIKE 'A%' OR HSDW.HelpTag LIKE 'B%' OR HSDW.HelpTag LIKE 'C%' OR HSDW.HelpTag LIKE 'D%' OR HSDW.HelpTag LIKE 'E%' OR HSDW.HelpTag LIKE 'F%' OR HSDW.HelpTag LIKE 'H%') AND (WLDW.HelpTag LIKE 'Z0%') AND (YE.ZWSSFZYE_KMBH LIKE '6001%') AND WLDW.LSWLDW_NBDW='1' AND ZWSSFZYE_KJQJ='<!KJQJ!>')

E4
SUM(BB(E3))

A6
SQL(SELECT YE.ZWSSFZYE_DWBH,HSDW.LSWLDW_DWMC,YE.ZWSSFZYE_WLDWBH,WLDW.LSWLDW_DWMC,ZWSSFZYE_JFLJ FROM ZWSSFZYE@YY@ YE LEFT JOIN LSWLDW HSDW ON HSDW.LSWLDW_WLDWBH=YE.ZWSSFZYE_DWBH LEFT JOIN LSWLDW WLDW ON WLDW.LSWLDW_WLDWBH=YE.ZWSSFZYE_WLDWBH WHERE (HSDW.HelpTag LIKE 'A%' OR HSDW.HelpTag LIKE 'B%' OR HSDW.HelpTag LIKE 'C%' OR HSDW.HelpTag LIKE 'D%' OR HSDW.HelpTag LIKE 'E%' OR HSDW.HelpTag LIKE 'F%' OR HSDW.HelpTag LIKE 'H%') AND (WLDW.HelpTag LIKE 'Z0%') AND (YE.ZWSSFZYE_KMBH LIKE '6401%') AND WLDW.LSWLDW_NBDW='1' AND ZWSSFZYE_KJQJ='<!KJQJ!>')

E7
SUM(BB(E6))

B9
SQL(SELECT SUM(ZWSSKMYE_JFLJ) FROM ZWSSKMYE2023 YE LEFT JOIN LSWLDW HSDW ON HSDW.LSWLDW_WLDWBH=YE.ZWSSKMYE_DWBH WHERE (HSDW.HelpTag LIKE 'Z0%') AND (ZWSSKMYE_KMBH='6401') AND ZWSSKMYE_KJQJ='12')

C9
SQL(SELECT SUM(ZWSSKMYE_JFLJ) FROM ZWSSKMYE@YY@ YE LEFT JOIN LSWLDW HSDW ON HSDW.LSWLDW_WLDWBH=YE.ZWSSKMYE_DWBH WHERE (HSDW.HelpTag LIKE 'Z0%') AND (ZWSSKMYE_KMBH='6401') AND ZWSSKMYE_KJQJ='<!KJQJ!>')

E9
BB(B9)+BB(C9)

B10
SQL(SELECT SUM(ZWSSKMYE_DFLJ) FROM ZWSSKMYE2023 YE LEFT JOIN LSWLDW HSDW ON HSDW.LSWLDW_WLDWBH=YE.ZWSSKMYE_DWBH WHERE (HSDW.HelpTag LIKE 'Z0%') AND (ZWSSKMYE_KMBH>'500201Z' AND ZWSSKMYE_KMBH<'500207Z' AND LEN(ZWSSKMYE_KMBH)=6) AND ZWSSKMYE_KJQJ='12')

C10
SQL(SELECT SUM(ZWSSKMYE_DFLJ) FROM ZWSSKMYE@YY@ YE LEFT JOIN LSWLDW HSDW ON HSDW.LSWLDW_WLDWBH=YE.ZWSSKMYE_DWBH WHERE (HSDW.HelpTag LIKE 'Z0%') AND (ZWSSKMYE_KMBH>'500201Z' AND ZWSSKMYE_KMBH<'500207Z' AND LEN(ZWSSKMYE_KMBH)=6) AND ZWSSKMYE_KJQJ='<!KJQJ!>')

D10
SQL(SELECT SUM(ZWSSKMYE_DQYE) FROM ZWSSKMYE@YY@ YE LEFT JOIN LSWLDW HSDW ON HSDW.LSWLDW_WLDWBH=YE.ZWSSKMYE_DWBH WHERE (HSDW.HelpTag LIKE 'Z0%') AND (ZWSSKMYE_KMBH>'500201Z' AND ZWSSKMYE_KMBH<'500207Z' AND LEN(ZWSSKMYE_KMBH)=6) AND ZWSSKMYE_KJQJ='<!KJQJ!>')

E10
BB(B10)+BB(C10)+BB(D10)

E11
BB(E9)/BB(E10)